### ISSUE TITLE
Remove the setting "Order status - if Payment is completed immediately" 

### ISSUE THREAD

**Issue by lb-altapay-com** [AltaPay/magento2#13]
As I understand the Magento documentation, the status "Complete" is only used, for when the items have been shipped, so I don't see any reason on why, the merchants would be able to set the status of the order to "Complete".

**Comment by lsv** [comment]
If the "Auto capture" is on (a setting for each terminal)
(The help text for this checkbox is: "If you only sell download products, which are delivered immediately you can turn this on")

Then the the order is completed immediately, due to the products are download products.

But I have removed the completed setting
