### ISSUE TITLE
No tax information in orderlines

### ISSUE THREAD

**Issue by lb-altapay-com** [AltaPay/magento2#16]
There is no tax informatiin like tax amount or tax procent in the ordersline. This is required by some payment methods.

**Comment by lsv** [comment]
The following fields are available on a order product

```
$item->getPrice(),
$item->getPriceInclTax(),
$item->getBasePrice(),
$item->getBaseOriginalPrice(),
$item->getGwBasePrice(),
$item->getGwPrice(),
$item->getOriginalPrice(),
$item->getDiscountAmount(),
$item->getBaseDiscountAmount()
```

Tax percent is not available, I can do a `getPriceInclTax() - getBasePrice()`  to get the tax price - Do @lb-altapay-com want that?

**Comment by lb-altapay-com** [comment]
Yes, that is fine. Please remember, that the tax amount, if the full tax amount for that orderlines. In this case, where the order two items off 100kr.

Then the unit price it 80, but the tax amount is 40. As the tax amount is for both items.

**Comment by lsv** [comment]
![selection_070](https://user-images.githubusercontent.com/20708/33999699-7657725a-e0eb-11e7-98d7-8fcec578bf5d.png)

For this product

I have the following variables

```
SKU: WP13-29-Blue
getPrice: 39.2000
getPriceInclTax: 49.0000
getBasePrice: 39.2000
getBaseOriginalPrice: 49.0000
getGwBasePrice: <empty>
getGwPrice: <empty>
getOriginalPrice: 49.0000
getDiscountAmount: 0.0000
getBaseDiscountAmount: 0.0000
```

Be aware, that the actual discount is NOT added to the product, due to this is a catalog discount.
The only way magento tells if there is a discount is if you add a fx coupon code in checkout (this is called a cart discount)

**Comment by lsv** [comment]
The following has been recieved to you.
Ordered 2 of the above blue product, and 1 green (same price)

Shipping is 15 flat rate (no tax on shipping)

```
orderLines[0][description]: | Portia Capri
-- | --
orderLines[0][itemId]: | WP13-29-Blue
orderLines[0][quantity]: | 2.0000
orderLines[0][unitPrice]: | 98
orderLines[0][taxAmount]: | 19.6
orderLines[0][goodsType]: | item
orderLines[1][description]: | Portia Capri
orderLines[1][itemId]: | WP13-29-Green
orderLines[1][quantity]: | 1.0000
orderLines[1][unitPrice]: | 49
orderLines[1][taxAmount]: | 9.8
orderLines[1][goodsType]: | item
orderLines[2][description]: | flatrate
orderLines[2][itemId]: | flatrate
orderLines[2][quantity]: | 1
orderLines[2][unitPrice]: | 15.0000
orderLines[2][goodsType]: | shipment
```

![selection_073](https://user-images.githubusercontent.com/20708/34000487-be124faa-e0ed-11e7-9c48-45a6b5ce2950.png)

There CAN be some rounding issues due to Magento tax converter, and also multipying number of items to get the tax amount.
